title: "CHISCO VALDÉS"
email: "hello@callmepapi.art"
description: "Filmmaker & Visual Artist. My friends call me papi."
baseurl: ""
url: "https://www.callmepapi.art"

# Keep Jekyll simple. You’re using custom layouts/CSS.
# theme: minima
# plugins:
#   - jekyll-feed
